language: cpp
dist: xenial
compiler: clang
git:
  depth: false
  gitsubmodules: false

stages:
  - Base
  - Lint
  - Test
  - Benchmark

matrix:
  include:
    - name: verifying travis.yml file
      stage: Base
      script:
        -  python3 .travis_gen.py > expected.out 
        -  diff .travis.yml expected.out 
    - name: compile libsat
      stage: Base
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make -C libsat "
      after_script:
        - docker stop cpp
    - name: compile libsat fast
      stage: Base
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make -C libsat fast "
      after_script:
        - docker stop cpp
    - name: compile sat
      stage: Base
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make -C sat "
      after_script:
        - docker stop cpp
    - name: compile sat fast
      stage: Base
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make -C sat fast "
      after_script:
        - docker stop cpp
    - name: uncrustify
      stage: Lint
      script:
        -  make uncrustify_check 
    - name: cpplint
      stage: Lint
      install:
        - sudo apt update 
        - sudo apt-get install -y --no-install-recommends python3-venv 
      script:
        -  make cpplint_run 
    - name: cppcheck
      stage: Lint
      install:
        - sudo apt update 
        - sudo apt-get install -y --no-install-recommends cppcheck 
      script:
        -  make cppcheck_run 
    - name: clang-tidy
      stage: Lint
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      install:
        - docker exec -t cpp bash -c " apt update "
        - docker exec -t cpp bash -c " apt-get install -y --no-install-recommends clang-tidy-6.0 clang-6.0 "
      script:
        - docker exec -t cpp bash -c " make clang_tidy_run "
      after_script:
        - docker stop cpp
    - name: sat cdcl RND3SAT 01 - 09
      stage: Test
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make satlib_bench "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_01_RND3SAT__uf20-91 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_02_RND3SAT__uf50-218 "
        - docker exec -t cpp bash -c " make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_03_RND3SAT__uuf50-218 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_04_RND3SAT__uf75-325 "
        - docker exec -t cpp bash -c " make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_05_RND3SAT__uuf75-325 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_06_RND3SAT__uf100-430 "
        - docker exec -t cpp bash -c " make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_07_RND3SAT__uuf100-430 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_08_RND3SAT__uf125-538 "
        - docker exec -t cpp bash -c " make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_09_RND3SAT__uuf125-538 "
      after_script:
        - docker stop cpp
    - name: sat cdcl BMS 20 - 21
      stage: Test
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make satlib_bench "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_20_BMS__RTI_k3_n100_m429 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_21_BMS__BMS_k3_n100_m429 "
      after_script:
        - docker stop cpp
    - name: sat cdcl CBS 22 - 31
      stage: Test
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make satlib_bench "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_22_CBS__CBS_k3_n100_m403_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_23_CBS__CBS_k3_n100_m403_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_24_CBS__CBS_k3_n100_m403_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_25_CBS__CBS_k3_n100_m403_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_26_CBS__CBS_k3_n100_m403_b90 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_27_CBS__CBS_k3_n100_m411_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_28_CBS__CBS_k3_n100_m411_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_29_CBS__CBS_k3_n100_m411_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_30_CBS__CBS_k3_n100_m411_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_31_CBS__CBS_k3_n100_m411_b90 "
      after_script:
        - docker stop cpp
    - name: sat cdcl CBS 32 - 41
      stage: Test
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make satlib_bench "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_32_CBS__CBS_k3_n100_m418_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_33_CBS__CBS_k3_n100_m418_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_34_CBS__CBS_k3_n100_m418_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_35_CBS__CBS_k3_n100_m418_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_36_CBS__CBS_k3_n100_m418_b90 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_37_CBS__CBS_k3_n100_m423_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_38_CBS__CBS_k3_n100_m423_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_39_CBS__CBS_k3_n100_m423_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_40_CBS__CBS_k3_n100_m423_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_41_CBS__CBS_k3_n100_m423_b90 "
      after_script:
        - docker stop cpp
    - name: sat cdcl CBS 42 - 51
      stage: Test
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make satlib_bench "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_42_CBS__CBS_k3_n100_m429_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_43_CBS__CBS_k3_n100_m429_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_44_CBS__CBS_k3_n100_m429_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_45_CBS__CBS_k3_n100_m429_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_46_CBS__CBS_k3_n100_m429_b90 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_47_CBS__CBS_k3_n100_m435_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_48_CBS__CBS_k3_n100_m435_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_49_CBS__CBS_k3_n100_m435_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_50_CBS__CBS_k3_n100_m435_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_51_CBS__CBS_k3_n100_m435_b90 "
      after_script:
        - docker stop cpp
    - name: sat cdcl CBS 52 - 61
      stage: Test
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make satlib_bench "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_52_CBS__CBS_k3_n100_m441_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_53_CBS__CBS_k3_n100_m441_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_54_CBS__CBS_k3_n100_m441_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_55_CBS__CBS_k3_n100_m441_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_56_CBS__CBS_k3_n100_m441_b90 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_57_CBS__CBS_k3_n100_m449_b10 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_58_CBS__CBS_k3_n100_m449_b30 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_59_CBS__CBS_k3_n100_m449_b50 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_60_CBS__CBS_k3_n100_m449_b70 "
        - docker exec -t cpp bash -c " make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_61_CBS__CBS_k3_n100_m449_b90 "
      after_script:
        - docker stop cpp
    - name: queens 1 - 21
      stage: Benchmark
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make -C sat fast "
        - docker exec -t cpp bash -c " time sat/sat queens 1 "
        - docker exec -t cpp bash -c " time sat/sat queens 2 "
        - docker exec -t cpp bash -c " time sat/sat queens 3 "
        - docker exec -t cpp bash -c " time sat/sat queens 4 "
        - docker exec -t cpp bash -c " time sat/sat queens 5 "
        - docker exec -t cpp bash -c " time sat/sat queens 6 "
        - docker exec -t cpp bash -c " time sat/sat queens 7 "
        - docker exec -t cpp bash -c " time sat/sat queens 8 "
        - docker exec -t cpp bash -c " time sat/sat queens 9 "
        - docker exec -t cpp bash -c " time sat/sat queens 10 "
        - docker exec -t cpp bash -c " time sat/sat queens 11 "
        - docker exec -t cpp bash -c " time sat/sat queens 12 "
        - docker exec -t cpp bash -c " time sat/sat queens 13 "
        - docker exec -t cpp bash -c " time sat/sat queens 14 "
        - docker exec -t cpp bash -c " time sat/sat queens 15 "
        - docker exec -t cpp bash -c " time sat/sat queens 16 "
        - docker exec -t cpp bash -c " time sat/sat queens 17 "
        - docker exec -t cpp bash -c " time sat/sat queens 18 "
        - docker exec -t cpp bash -c " time sat/sat queens 19 "
        - docker exec -t cpp bash -c " time sat/sat queens 20 "
        - docker exec -t cpp bash -c " time sat/sat queens 21 "
      after_script:
        - docker stop cpp
    - name: PHP 1 - 8
      stage: Benchmark
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make -C sat fast "
        - docker exec -t cpp bash -c " time sat/sat PHP 1 "
        - docker exec -t cpp bash -c " time sat/sat PHP 2 "
        - docker exec -t cpp bash -c " time sat/sat PHP 3 "
        - docker exec -t cpp bash -c " time sat/sat PHP 4 "
        - docker exec -t cpp bash -c " time sat/sat PHP 5 "
        - docker exec -t cpp bash -c " time sat/sat PHP 6 "
        - docker exec -t cpp bash -c " time sat/sat PHP 7 "
        - docker exec -t cpp bash -c " time sat/sat PHP 8 "
      after_script:
        - docker stop cpp
    - name: einstein
      stage: Benchmark
      before_install:
        - docker build -t cpp .
        - docker run --rm --detach --volume `pwd`:/code --workdir /code --name cpp cpp tail -f /dev/null
      script:
        - docker exec -t cpp bash -c " make -C sat fast "
        - docker exec -t cpp bash -c " sat/sat einstein "
      after_script:
        - docker stop cpp
