# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jpriou <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/17 09:12:53 by jpriou            #+#    #+#              #
#    Updated: 2017/08/17 14:12:57 by jpriou           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_tail
FILES_FT = ftlib/ft_putstr.c ftlib/ft_strcmp.c ftlib/ft_atoi.c
FILES_MAIN = main.c

all :
	gcc -o $(NAME) $(FILES_FT) $(FILES_MAIN) -I ./
clean :
	rm -f $(NAME)
fclea : clean
