---
sudo: disabled
language: c
os: linux
after_script: make fclean
stage:
- Verify .travis.yml
- Build
- Build custom
- All
matrix:
    include:
    -   stage: Verify .travis.yml
        script:
        - apt-get install -y python3-yaml
        - python3 scripts/gen_travis_file.py test.out
        - diff test.out .travis.yml
        - rm -f test.out
        after_script: make fclean
        env:
            NAME: Use python script to verify
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=5
        after_script: make fclean
        env:
            NAME: Build libft with gcc 5
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=6
        after_script: make fclean
        env:
            NAME: Build libft with gcc 6
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=7
        after_script: make fclean
        env:
            NAME: Build libft with gcc 7
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=8
        after_script: make fclean
        env:
            NAME: Build libft with gcc 8
    -   stage: Build
        script: make -C libft test_docker_compile_gcc
        after_script: make fclean
        env:
            NAME: Build libft with gcc latest
    -   stage: Build
        script: make -C libft test_docker_compile_clang
        after_script: make fclean
        env:
            NAME: Build libft with clang (latest on Debian)
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=5 TEST_CMD="make
            so"
        after_script: make fclean
        env:
            NAME: Build libft with gcc 5 (make so)
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=6 TEST_CMD="make
            so"
        after_script: make fclean
        env:
            NAME: Build libft with gcc 6 (make so)
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=7 TEST_CMD="make
            so"
        after_script: make fclean
        env:
            NAME: Build libft with gcc 7 (make so)
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=8 TEST_CMD="make
            so"
        after_script: make fclean
        env:
            NAME: Build libft with gcc 8 (make so)
    -   stage: Build
        script: make -C libft test_docker_compile_gcc TEST_CMD="make so"
        after_script: make fclean
        env:
            NAME: Build libft with gcc latest (make so)
    -   stage: Build
        script: make -C libft test_docker_compile_clang TEST_CMD="make so"
        after_script: make fclean
        env:
            NAME: Build libft with clang (latest on Debian) (make so)
    -   stage: Build
        script: make build_custom
        after_script: make fclean
        env:
            NAME: Build build_custom
    -   stage: Build custom
        script: make -C tests/build_custom/ all
        after_script: make fclean
        env:
            NAME: Build Custom All
    -   stage: All
        script: make testall
        after_script: make fclean
        env:
            NAME: All script
...
