language: C
dist: xenial

stages:
  - Base
  - Lint
  - Test

matrix:
  include:
    - name: verifying travis.yml file
      stage: Base
      script:
        - python3 .travis_gen.py > expected.out
        - diff .travis.yml expected.out
    - name: compile libsat
      stage: Base
      script:
        - make -C libsat
    - name: compile sat
      stage: Base
      script:
        - make -C sat
    - name: uncrustify
      stage: Lint
      script:
        - make uncrustify_check
    - name: cpplint
      stage: Lint
      before_install: sudo apt-get update
      install:
        - sudo apt-get install -y --no-install-recommends python3-venv
      script:
        - make cpplint_run
    - name: cppcheck
      stage: Lint
      before_install: sudo apt-get update
      install:
        - sudo apt-get install -y --no-install-recommends cppcheck
      script:
        - make cppcheck_run
    - name: clang-tidy
      stage: Lint
      before_install: sudo apt-get update
      install:
        - sudo apt-get install -y --no-install-recommends clang-tidy-6.0 clang-6.0
      script:
        - travis_retry make clang_tidy_run
    - name: check sat dpll
      stage: Test
      script:
        - make satlib_bench
        - make -C tests FOLDER_CNFS=../input_files/satlib/_01_RND3SAT__uf20-91
