language: c

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install -y --no-install-recommends
        python3.4-venv
    - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.9.tar.gz | tar xz;
        cd SDL2-2.0.9;
        ./configure;
        make;
        sudo make install;
        cd ..;
        rm -rf SDL2-2.0.9

matrix:
    include:
        - name: check uncrustify
          script: make uncrustify_check
        - name: run cpplint
          script: make cpplint_run
        - name: make
          script: make
