language: c
matrix:
    include:
        - name: check uncrustify
          script: make uncrustify_check
        - name: run cpplint
          install: apt-get install -y --no-install-recommends python3-venv
          script: make cpplint_run
