sudo : disabled
language : c
compiler :
  - gcc
  - cc
  - clang

script : make
after_script : make fclean

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
         - MATRIX_EVAL="CC=gcc"
         - NAME="Single Compile test"
    - os: linux
      script : make -C tests/build_custom/ 10
      env :
         - NAME="Full Build Custom 11--16"
    - os: linux
      script : make -C tests/build_custom/ 11
      env :
         - NAME="Build Custom 11"
    - os: linux
      script : make -C tests/build_custom/ 12
      env :
         - NAME="Build Custom 12"
    - os: linux
      script : make -C tests/build_custom/ 13
      env :
         - NAME="Build Custom 13"
    - os: linux
      script : make -C tests/build_custom/ 14
      env :
         - NAME="Build Custom 14"
    - os: linux
      script : make -C tests/build_custom/ 15
      env :
         - NAME="Build Custom 15"
    - os: linux
      script : make -C tests/build_custom/ 16
      env :
         - NAME="Build Custom 16"
    - os: linux
      script : make -C tests/build_custom/ 20
      env :
         - NAME="Full Build Custom 21--24"
    - os: linux
      script : make -C tests/build_custom/ 21
      env :
         - NAME="Build Custom 21"
    - os: linux
      script : make -C tests/build_custom/ 22
      env :
         - NAME="Build Custom 22"
    - os: linux
      script : make -C tests/build_custom/ 23
      env :
         - NAME="Build Custom 23"
    - os: linux
      script : make -C tests/build_custom/ 24
      env :
         - NAME="Build Custom 24"
