language: c
matrix:
    include:
        - name: check uncrustify
          script: make uncrustify_check
        - name: run cpplint
          before_install:
            - sudo apt-get update
            - sudo apt-get upgrade -y
          install: sudo apt-get install -y --no-install-recommends python3-venv
          script: make cpplint_run
