---
sudo: disabled
language: c
os: linux
after_script: make fclean
stage:
- Verify .travis.yml
- Build
- Final
matrix:
    include:
    -   stage: Verify .travis.yml
        script:
        - python scripts/gen_travis_file.py > test.out
        - diff test.out .travis.yml
        - rm -f test.out
        after_script: make fclean
        env:
            NAME: Use python script to verify
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=5
        after_script: make fclean
        env:
            NAME: Build libft with gcc 5
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=6
        after_script: make fclean
        env:
            NAME: Build libft with gcc 6
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=7
        after_script: make fclean
        env:
            NAME: Build libft with gcc 7
    -   stage: Build
        script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=8
        after_script: make fclean
        env:
            NAME: Build libft with gcc 8
    -   stage: Build
        script: make -C libft test_docker_compile_gcc
        after_script: make fclean
        env:
            NAME: Build libft with gcc latest
    -   stage: Build
        script: make -C libft test_docker_compile_clang
        after_script: make fclean
        env:
            NAME: Build libft with clang (latest on Debian)
    -   stage: Build
        script: make build_custom
        after_script: make fclean
        env:
            NAME: Build build_custom
    -   stage: Final
        script: make -C tests/build_custom/ all
        after_script: make fclean
        env:
            NAME: Full Build Custom All
...

