sudo : disabled
language : c
os: linux

script : make libft
after_script : make fclean

stages:
    - build
    - build_custom_test
    - ctestcom_test
    - final

matrix:
  include:
    - stage: build
      env:
        - NAME="Test GCC"
        - CC="gcc"
    - stage: build
      env:
        - NAME="Test CC"
        - CC="cc"
    - stage: build
      env:
        - NAME="Test CLANG"
        - CC="clang"
    - stage: build
      script: make ctestcom
      env:
        - NAME="Build Ctestcom"
    - stage: build_custom_test
      script : make -C tests/build_custom/ 10
      env :
        - NAME="Full Build Custom 10"
    - stage: build_custom_test
      script : make -C tests/build_custom/ 20
      env :
        - NAME="Full Build Custom 20"
    - stage: build_custom_test
      script : make -C tests/build_custom/ 30
      env :
        - NAME="Full Build Custom 30"
    - stage: ctestcom_test
      script : make -C ctestcom testctestcom
      env :
       - NAME="CtestCom main test in"
    - stage: final
      script : make -C tests/build_custom/ all
      env :
        - NAME="Full Build Custom All"
