sudo : disabled
language : c
compiler :
  - gcc
  - cc
  - clang

script : make -C libft
after_script : make -C libft fclean

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
         - MATRIX_EVAL="CC=gcc"
         - NAME="Single Compile test"
    - os: linux
      script : make -C tests/build_custom/ 0
      env :
         - NAME="Full Build Custom All"
    - os: linux
      script : make -C tests/build_custom/ 10
      env :
         - NAME="Full Build Custom 11--16"
    - os: linux
      script : make -C tests/build_custom/ 20
      env :
         - NAME="Full Build Custom 21--24"
    - os: linux
      script : make -C tests/build_custom/ 30
      env :
         - NAME="Full Build Custom 31--35"
    - os: linux
      script : make -C ctestcom testctestcom
      env :
         - NAME="CtestCom main test in"
