sudo : disabled
language : c
os: linux

script : make libft
after_script : make fclean

stages:
    - build
    - build_custom_test
    - ctestcom_test
    - final

matrix:
  include:
    - stage: build
      script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=5
      env:
        - NAME="Build libft gcc 5"
    - stage: build
      script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=6
      env:
        - NAME="Build libft gcc 6"
    - stage: build
      script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=7
      env:
        - NAME="Build libft gcc 7"
    - stage: build
      script: make -C libft test_docker_compile_gcc VERSION_GCC_DOCKER=8
      env:
        - NAME="Build libft gcc 8"
    - stage: build
      script: make -C libft test_docker_compile_gcc
      env:
        - NAME="Build libft gcc latest"
    - stage: build
      script: make -C libft test_docker_compile_clang
      env:
        - NAME="Build libft clang latest (on Debian)"
    - stage: build
      script: make ctestcom
      env:
        - NAME="Build Ctestcom"
    - stage: build_custom_test
      script : make -C tests/build_custom/ 10
      env :
        - NAME="Full Build Custom 10"
    - stage: build_custom_test
      script : make -C tests/build_custom/ 20
      env :
        - NAME="Full Build Custom 20"
    - stage: build_custom_test
      script : make -C tests/build_custom/ 30
      env :
        - NAME="Full Build Custom 30"
    - stage: ctestcom_test
      script : make -C ctestcom testctestcom
      env :
       - NAME="CtestCom main test in"
    - stage: final
      script : make -C tests/build_custom/ all
      env :
        - NAME="Full Build Custom All"
