language: C
dist: xenial

stages:
  - Base
  - Lint
  - Test
  - Benchmark

matrix:
  include:
    - name: verifying travis.yml file
      stage: Base
      script:
        - python3 .travis_gen.py > expected.out
        - diff .travis.yml expected.out
    - name: compile libsat
      stage: Base
      script:
        - make -C libsat
    - name: compile libsat fast
      stage: Base
      script:
        - make -C libsat fast
    - name: compile sat
      stage: Base
      script:
        - make -C sat
    - name: compile sat fast
      stage: Base
      script:
        - make -C sat fast
    - name: uncrustify
      stage: Lint
      script:
        - make uncrustify_check
    - name: cpplint
      stage: Lint
      before_install: sudo apt-get update
      install:
        - sudo apt-get install -y --no-install-recommends python3-venv
      script:
        - make cpplint_run
    - name: cppcheck
      stage: Lint
      before_install: sudo apt-get update
      install:
        - sudo apt-get install -y --no-install-recommends cppcheck
      script:
        - make cppcheck_run
    - name: clang-tidy
      stage: Lint
      before_install: sudo apt-get update
      install:
        - sudo apt-get install -y --no-install-recommends clang-tidy-6.0 clang-6.0
      script:
        - travis_retry make clang_tidy_run
    - name: sat dpll RND3SAT 01 - 09
      stage: Test
      script:
        - make satlib_bench
        - make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_01_RND3SAT__uf20-91
        - make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_02_RND3SAT__uf50-218
        - make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_03_RND3SAT__uuf50-218
        - make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_04_RND3SAT__uf75-325
        - make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_05_RND3SAT__uuf75-325
        - make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_06_RND3SAT__uf100-430
        - make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_07_RND3SAT__uuf100-430
        - make -C tests test_sat FOLDER_CNFS=../input_files/satlib/_08_RND3SAT__uf125-538
        - make -C tests test_unsat FOLDER_CNFS=../input_files/satlib/_09_RND3SAT__uuf125-538
    - name: queens
      stage: Benchmark
      script:
        - make -C sat fast
        - time (echo 1 | sat/sat queens)
        - time (echo 2 | sat/sat queens)
        - time (echo 3 | sat/sat queens)
        - time (echo 4 | sat/sat queens)
        - time (echo 5 | sat/sat queens)
        - time (echo 6 | sat/sat queens)
        - time (echo 7 | sat/sat queens)
        - time (echo 8 | sat/sat queens)
        - time (echo 9 | sat/sat queens)
        - time (echo 10 | sat/sat queens)
        - time (echo 11 | sat/sat queens)
        - time (echo 12 | sat/sat queens)
        - time (echo 13 | sat/sat queens)
        - time (echo 14 | sat/sat queens)
        - time (echo 15 | sat/sat queens)
        - time (echo 16 | sat/sat queens)
        - time (echo 17 | sat/sat queens)
        - time (echo 18 | sat/sat queens)
        - time (echo 19 | sat/sat queens)
        - time (echo 20 | sat/sat queens)
        - time (echo 21 | sat/sat queens)
