language: c
matrix:
    include:
        - name: check uncrustify
          env: NAME="check uncrustify"
          script: make uncrustify_check
        - name: run cpplint
          env: NAME="run cpplint"
          script: make cpplint_run
