#!/bin/sh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# $1 is a name
# $2 is a first command to be ran
# $3 is a second one

function doit {
  echo -e "${RED}[$1...]${NC}"
  $2
  if [ $? -ne 0 ]; then
    echo -e "${RED}$1 FAILED${NC}"
    exit 1;
  fi
  $3
  echo -e "${GREEN}[$1 SUCCESSED]${NC}"
}

doit "NORMALISE" "make norm" "git diff"
doit "GENDOC" "make doc" "" 

git add -A
