# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jpriou <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/14 13:36:45 by jpriou            #+#    #+#              #
#    Updated: 2017/08/14 17:00:23 by jpriou           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
ALL_FILES_FT = ft_putchar.c ft_putstr.c ft_atoi.c ft_putnbr.c
ALL_FILES_MAIN = main.c operation.c

all :
	gcc -Wall -Wextra -Werror $(ALL_FILES_MAIN) $(ALL_FILES_FT) -o $(NAME)
clean :
	rm -f $(NAME)
